### ISSUE TITLE
Not really an Issue, but maybe you can help?

### ISSUE THREAD

**Issue by friesofdoom** [clemy/vulkan-video-encode-simple#1]
Thank you so much this is the best example code I've found for getting video encoding working, how did you even figure it all out? I've spent weeks trying to get the nvpro example to work but the code is an absolute mess. Your example is a masterpiece.

I have a strange issue that you might be able to help with though - I'm using vulkan video encoding to send rendered video to a web browser. I'm using webcodecs VideoDecoder to decode the stream, and this worked fine when I was using nvidia's h264 encoder but it cant seem to decode the vulkan video NALUs no matter what profile settings I use. The NALU's all look fine coming from the encoder, and VLC can decode the stream. The WebCodecs configuration codec string is good, and matches what is in the SPS data. I was wondering if you might have any ideas why WebCodec VideoDecoder wont decode the NALUs?

Thanks!

**Comment by clemy** [comment]
Hi,
Thank you for your feedback. I am happy that my example could help you!

Regarding your specific question: Unfortunately I am not an expert in WebCodec, so I am not sure if I can help you with that.
I did not find a WebCodec example for H264 ES streams, but the best I could do is mux the output of my Vulkan Encoder Example
with
`ffmpeg -framerate 30 -i hwenc.264 -c copy hwenc.mp4`
into an MP4 file (without changing the H264 frames) and then playing it with the example from
https://github.com/w3c/webcodecs/tree/main/samples/video-decode-display
This worked for me. Maybe you can use a similar way (via MP4 and that example) to get the WebCodecs configuration string and compare it with yours?

**Comment by friesofdoom** [comment]
Thanks! After messing with codec strings for hours and not getting anywhere I randomly tried sending the sps nalu and first frame nalu as a single combined chunk and it magically works.
